### ISSUE TITLE
Komodo incompatible with GNOME on RHEL7

### ISSUE THREAD

**Issue by oyvindeide** [equinor/komodo#97] opened 2020-04-22 10:52 UTC
Komodo is incompatible with GNOME on RHEL7 if sourced in a  `.*rc`-file, because that is sourced from `.*_profile`, and the python version overwrites the system default.

Known issues:
 - [ ] gnome-tweaks
 - [ ] frozen login screen

**Comment by berland** [comment] 2020-04-22 12:28
By using
```
tty -s && source /prog/res/komodo/testing-py36/enable
```
the problem seemingly goes away, at least I can login, komodo is correctly activated  in terminals. Not tested through ERT/LSF (where this sourcing then probably will not happen, but you said this is fixed by other means?)

**Comment by dotfloat** [comment] 2020-04-22 14:53
Found out that `LD_LIBRARY_PATH` is the problem. Other projects (https://github.com/pyenv/pyenv, maybe conda) can insert their own Pythons without issue. The problem is that libraries conflict with the system. Initialising komodo with the following fixes both GNOME log in and KDE font sizes:
```bash
_ld=$LD_LIBRARY_PATH
source /prog/res/komodo/bleeding-py36/enable
export LD_LIBRARY_PATH=$_ld
```
While `python` is Komodo's.

I propose the following solution:
1. Komodo's `enable` only sets `PATH` and `PS1`.
2. `PATH` points to `root/shims` instead of `root/bin`
3. All files in `root/shims` are wrappers for files in `root/bin`. The difference is that they set `LD_LIBRARY_PATH` (if not set before)

Alternatively, we can fix the RPATH for all libraries that use Komodo's libs so that we don't need to set `LD_LIBRARY_PATH`.

**Comment by dotfloat** [comment] 2020-04-23 10:01
Here's a list of libraries (only `.so` files) in komodo that have missing dependencies:
https://gist.github.com/dotfloat/88f50045398a170d0642efd1a31fbee8

Notice that all of these are either our software or are built by us. Some oddities: PyQt5's Python extension libraries all have their RPATH set to `/project/res/komodo/repository/qt5/root/lib` and these are the ones that get loaded. That is, the libraries `/prog/res/komodo/testing-py36/root/lib/libQt5*.so` are entirely unused.

We should compile things with RPATH enable when possible: this would have to be a change in the `kmd` tool. For software that we rsync in, we can use https://github.com/NixOS/patchelf to patch the RPATH.

**Comment by markusdregi** [comment] 2020-08-05 08:15
This has been solved

**Closed by markusdregi** 2020-08-05 08:16 UTC
